config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :item_types
  devise_for :users

  root to: 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_type, optional: true
  belongs_to :user
end

app/models/item_type.rb
class ItemType < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # provided by devise
  # authenticate user
  #   before_action :authenticate_user!
  # verify if a user is signed in
  #   user_signed_in?
  # current signed in user
  #   current_user
  # access session for this scope
  #   user_session
end

app/controllers/item_types_controller.rb
class ItemTypesController < ApplicationController
  before_action :set_item_type, only: [:show, :edit, :update, :destroy]

  # GET /item_types
  # GET /item_types.json
  def index
    @item_types = ItemType.all
  end

  # GET /item_types/1
  # GET /item_types/1.json
  def show
  end

  # GET /item_types/new
  def new
    @item_type = ItemType.new
  end

  # GET /item_types/1/edit
  def edit
  end

  # POST /item_types
  # POST /item_types.json
  def create
    @item_type = ItemType.new(item_type_params)

    respond_to do |format|
      if @item_type.save
        format.html { redirect_to @item_type, notice: 'Item type was successfully created.' }
        format.json { render :show, status: :created, location: @item_type }
      else
        format.html { render :new }
        format.json { render json: @item_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_types/1
  # PATCH/PUT /item_types/1.json
  def update
    respond_to do |format|
      if @item_type.update(item_type_params)
        format.html { redirect_to @item_type, notice: 'Item type was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_type }
      else
        format.html { render :edit }
        format.json { render json: @item_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_types/1
  # DELETE /item_types/1.json
  def destroy
    @item_type.destroy
    respond_to do |format|
      format.html { redirect_to item_types_url, notice: 'Item type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_type
      @item_type = ItemType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_type_params
      params.require(:item_type).permit(:name, :description, :days_until_expiration)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @items = current_user.items.all.order(:expiration_date)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_url, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = current_user.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :expiration_date, :item_type_id, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def colorized_expiration_date(expiration_date)
    class_name = if expiration_date > 7.days.from_now
      "text-success"
    elsif expiration_date > 3.days.from_now
      "text-warning"
    else
      "text-danger"
    end

    formatted_date = expiration_date.strftime("%a %b #{expiration_date.day.ordinalize}")
    element = "<div class=#{class_name}>#{formatted_date}</div>"
    element.html_safe
  end

  def item_with_quantity(item)
    if item.quantity > 1
      "#{item.name} (#{item.quantity})"
    else
      "#{item.name}"
    end
  end
end

app/views/item_types/_form.html.erb
<%= form_with(model: item_type, local: true) do |form| %>
  <% if item_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_type.errors.count, "error") %> prohibited this item_type from being saved:</h2>

      <ul>
      <% item_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :days_until_expiration %>
    <%= form.number_field :days_until_expiration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_types/edit.html.erb
<h1>Editing Item Type</h1>

<%= render 'form', item_type: @item_type %>

<%= link_to 'Show', @item_type %> |
<%= link_to 'Back', item_types_path %>

app/views/item_types/index.html.erb
<h1>Item Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Days until expiration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_types.each do |item_type| %>
      <tr>
        <td><%= item_type.name %></td>
        <td><%= item_type.description %></td>
        <td><%= item_type.days_until_expiration %></td>
        <td><%= link_to 'Show', item_type %></td>
        <td><%= link_to 'Edit', edit_item_type_path(item_type) %></td>
        <td><%= link_to 'Destroy', item_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Type', new_item_type_path %>

app/views/item_types/new.html.erb
<h1>New Item Type</h1>

<%= render 'form', item_type: @item_type %>

<%= link_to 'Back', item_types_path %>

app/views/item_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item_type.description %>
</p>

<p>
  <strong>Days until expiration:</strong>
  <%= @item_type.days_until_expiration %>
</p>

<%= link_to 'Edit', edit_item_type_path(@item_type) %> |
<%= link_to 'Back', item_types_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :item_type_id %><br>
    <%= collection_select(:item, :item_type_id, ItemType.all, :id, :name, include_blank: true) %>
  </div> -->

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %><br>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %><br>
    <%= form.date_select :expiration_date, order: [:month, :day, :year], default: nil, class: 'form-control' %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="page-container">
  <h1 class="text-center text-cursive">Editing Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Back', items_path %>

</div>

app/views/items/index.html.erb
<div class="page-container">

<div class="items-header">
  <h2>In <span class="text-cursive">My Kitchen</span></h2>
  <%= button_tag image_tag("help.png", size: "40x40"), class: 'btn-help', data: {toggle: 'tooltip', html: true, placement: 'left', title: '<p class="text-danger">Expires in <b>less than 3 days</b></p><p class="text-warning">Expires in <b>less than 7 days</b></p><p class="text-success">Expires <b>after 7 days</b></p>' } %>
</div>

<% @items.each do |item| %>
  <div class="item-row" data-id="<%= item.id %>">
    <div><%= item_with_quantity(item) %></div>
    <%= colorized_expiration_date(item.expiration_date) %>
  </div>
  <div class="action-row">
    <div><%= link_to 'Show', item %></div>
    <div><%= link_to 'Edit', edit_item_path(item) %></div>
    <div><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></div>
  </div>
<% end %>

<br>

<div class="btn-new-container">
  <%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %>
</div>

app/views/items/new.html.erb
<div class="page-container">
  <h1 class="text-center text-cursive">New Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<% if @item.quantity > 1 %>
  <p>
    <strong>Quantity:</strong>
    <%= @item.quantity %>
  </p>
<% end %>

<p>
  <strong>Expiration date:</strong>
  <%= @item.expiration_date %>
</p>

<% if @item.item_type %>
  <p>
    <strong>Item type:</strong>
    <%= @item.item_type %>
  </p>
<% end %>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light sticky-top">
  <a class="navbar-brand" href="/">My Kitchen</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link <%= 'active' if current_page?(items_path) %>" href="/items">Items</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(item_types_path) %>">
        <a class="nav-link" href="/item_types">Item Types</a>
      </li>
      <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link text-danger') %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyKitchen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>